### ISSUE TITLE
Error building PyCall

### ISSUE THREAD

**Issue by markhalonen** [Optomatica/heroku-buildpack-julia#6]
For this open source project https://github.com/laurium-labs/coilgunui, I'm trying to host a HTTPS api that uses a bunch of Julia libraries like DiffEQ to simulate a coil gun.

I'm getting this error while trying to build:
```
remote: ┌ Error: Error building `PyCall`:
remote: │ ERROR: LoadError: Couldn't find libpython; check your PYTHON environment variable.
remote: │
remote: │ The python executable we tried was python3 (= version 3.6).
remote: │ Re-building with
remote: │     ENV["PYCALL_DEBUG_BUILD"] = "yes"
remote: │ may provide extra information for why it failed.
remote: │
remote: │ Stacktrace:
remote: │  [1] error(::String) at ./error.jl:33
remote: │  [2] find_libpython(::String; _dlopen::typeof(Libdl.dlopen)) at /app/.julia/packages/PyCall/zqDXB/deps/buildutils.jl:72
remote: │  [3] find_libpython(::String) at /app/.julia/packages/PyCall/zqDXB/deps/buildutils.jl:41
remote: │  [4] top-level scope at /app/.julia/packages/PyCall/zqDXB/deps/build.jl:87
remote: │  [5] include(::String) at ./client.jl:439
remote: │  [6] top-level scope at none:5
remote: │ in expression starting at /app/.julia/packages/PyCall/zqDXB/deps/build.jl:43
remote: └ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:899
```

I got this after adding the Python buildpack before this Julia buildpack, still getting the same error.

To reproduce:
```
git clone https://github.com/laurium-labs/coilgunui
cd coilgunui
heroku create --buildpack https://github.com/Optomatica/heroku-buildpack-julia.git
heroku git:remote -a HEROKU_PROJECT_NAME
git subtree push --prefix be heroku master
```
and then watch the build output. It gives the same error after adding Python buildpack in the ui:

![image](https://user-images.githubusercontent.com/7853605/89046359-d8e94c80-d31a-11ea-9bbf-d92b5c9af2c3.png)

Last year I had a similar issue and had to eventually resort to EC2 and manually setting up load balancers etc. in AWS... so I'm really hoping I can use this and don't have to do that again!! : https://medium.com/@markhalonen/deploying-julia-1eb8a1686ca1

**Comment by markhalonen** [comment]
it actually ignores the error and launches but then fails with 
```
2020-07-31T14:51:12.524348+00:00 heroku[web.1]: Starting process with command `julia --project src/server.jl 45064`
2020-07-31T14:51:55.243387+00:00 heroku[web.1]: Process running mem=1145M(223.8%)
2020-07-31T14:51:55.245774+00:00 heroku[web.1]: Error R15 (Memory quota vastly exceeded)
2020-07-31T14:51:55.248022+00:00 heroku[web.1]: Stopping process with SIGKILL
2020-07-31T14:51:55.435344+00:00 heroku[web.1]: Process exited with status 137
2020-07-31T14:51:55.471931+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by mbeltagy** [comment]
Sound like what you are doing is really memory intensive (specially on startup).... I suggest that you either:

- Reduce the memory footprint (if you can), or
 
- Get a Heroku premium instance with sufficiently large memory

You seem to be running with on hobby dyno with with 512mb limit. 
Try getting a bigger one, see: https://devcenter.heroku.com/articles/dyno-types

**Comment by markhalonen** [comment]
Found a solution that works great for me: https://discourse.julialang.org/t/deploying-julia-on-heroku-buildpacks-and-packagecompiler-failing/44043
