### ISSUE TITLE
Compats in Project.toml

### ISSUE THREAD

**Issue by benHeid** [Optomatica/heroku-buildpack-julia#7]
In my project toml und compat I have set `julia = "1"`. So I supposed 1.5.2 is fetched. However according to my building logs it tries to fetch julia 1.0

```
-----> Julia app detected
-----> Installing julia 1.0 ....        - julia-1.0-linux-x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
 !     Push rejected, failed to compile Julia app.
 !     Push failed```

**Comment by mbeltagy** [comment]
It does not work that way. It will not try to be clever in inferring the Julia version that you are after, so you have to be quite specific.
So if 1.5.2 is what you want you should have 
```toml
julia="1.5.2" 
``` 
in your `Project.toml` file.
